[build]
  publish = "public"
  command = ""

[functions]
  node_bundler = "esbuild"

  [functions.defaults]
    timeout = 26

[build.environment]
  MONGODB_URI = "YOUR_MONGODB_ATLAS_URI"
  JWT_SECRET = "your-super-secret-jwt-key-12345"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
